### ISSUE TITLE
login.qr ValueError: not enough value to unpack (expected 3 but got 2)

### ISSUE THREAD

**Issue by TimG233** [FengLiuFeseliud/pycloudmusic#3]
如果按照文档例子用qr code登录就是这个错误
terminal log
```
('...', 'https://music.163.com/login?codekey=...')
https://music.163.com/login?codekey=...
Traceback (most recent call last):
  File "... \netease_login_test.py", line 20, in <module>
    asyncio.run(netease_login())
  File "... \Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "... \Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "... \netease_login_test.py", line 14, in netease_login
    code, cookie, musicapi = await login.qr(qr_key[0])
ValueError: not enough values to unpack (expected 3, got 2)
```
而且这个代码提示里也会显示有问题，其实应该是2个才能unpack
`cookie, musicapi = await login.qr(qr_key[0])` 这样能成功unpack。
所以这个要不就是变成expected 2要不就加一个code

**Comment by FengLiuFeseliud** [comment]
之前把这个 code 删了感觉太多于了，删了之后没改文档，晚点改了
